/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Project ID is safe to keep in repo; keys should come from environment when possible.
export const projectId = "ooqgeiedqropzrvfxqjv";

// Prefer Vite env vars at build time (prefix VITE_) but fall back to the committed public anon key for dev.
export const publicAnonKey =
   import.meta.env.VITE_SUPABASE_ANON_KEY ??
   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcWdlaWVkcXJvcHpydmZ4cWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTg1MDAsImV4cCI6MjA3NjE5NDUwMH0.MiNKAN2qT-yRVCMORXLRl_FhJzmxmTC515_VHaRbToM";

// Full URL (also prefer env if provided)
export const supabaseUrl =
   import.meta.env.VITE_SUPABASE_URL ?? `https://${projectId}.supabase.co`;
