/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Add type declaration for ImportMeta.env (Vite)
interface ImportMetaEnv {
   VITE_SUPABASE_ANON_KEY?: string;
   VITE_SUPABASE_URL?: string;
}

declare global {
   interface ImportMeta {
      readonly env: ImportMetaEnv;
   }
}

// Project ID is safe to keep in repo; secrets MUST come from environment variables.
export const projectId = "ooqgeiedqropzrvfxqjv";

// Read env variables in a way that works both at build time (Vite import.meta.env)
// and in Node/server contexts (process.env). Do NOT keep secrets in source code.
// Use import.meta when available; otherwise fall back to process.env.
export const publicAnonKey =
   (import.meta as any)?.env?.VITE_SUPABASE_ANON_KEY ||
   process.env.VITE_SUPABASE_ANON_KEY ||
   "";

export const supabaseUrl =
   (import.meta as any)?.env?.VITE_SUPABASE_URL ||
   process.env.VITE_SUPABASE_URL ||
   `https://${projectId}.supabase.co`;
